In [8]:
import numpy as np
from model import MLP
import torch

In [9]:
config = np.array([[ 0.,          0.0534427,   0.05344266],
 [ 0.,         -0.10604769,  1.05260506],
 [ 0.,          1.05260499, -0.10604768],])
print(config)

[[ 0.          0.0534427   0.05344266]
 [ 0.         -0.10604769  1.05260506]
 [ 0.          1.05260499 -0.10604768]]


In [15]:
config = np.array([[0,0,0],[0,0,1],[0,1,0]])

In [16]:
#load the model
model = MLP()
model.load_state_dict(torch.load(r'weight\mlp_model_weights.pth'))


<All keys matched successfully>

In [17]:
#convert to tensor
config = torch.tensor(config, dtype=torch.float32)
config = config.reshape(1,9)
#predict
output = model(config)
print(output)



tensor([[-14.4851]], grad_fn=<AddmmBackward0>)


In [18]:
# predict force using gradient at the bottom layer
config.requires_grad = True
output = model(config)
output.backward()
print(config.grad)

tensor([[-564.2786, -242.9326, -234.5451,  263.0485,  -31.0158, -189.4107,
          353.0499,  274.3174,  628.7446]])
